_target_: src.pl_modules.model.MyModel
epochs: 500
seq_len: 200
batch_size: 32

# Optimisation
dropout: 0.5
momentum: 0.0005
weight_decay: 0.00005
scheduling: True
warm_up: 2

# num_samples: 50000
# Architecure optimisation

ninp: 2048
token_embedding: 1024
nhid: 2048
nlayers: 4
projection_size: 512
output_shape: 128
gpu: 3

# total, max, avg
pooling: "none"

# Data input
# img = 2048, location = 2048, motion = 512, audio = 128, all=4736

experts: ["test-video-embeddings", "test-location-embeddings", "test-img-embeddings", "audio-embeddings"]
train_experts: ["img-embeddings"]
test_experts: ["test-img-embeddings"]
# experts: ["location-embeddings", "img-embeddings", "video-embeddings", "audio-embeddings"]
ntoken: 15
nhead: 4
# pool or None
frame_agg: "none"
frame_id: 0

# Multi modal settings
mixing_method: "post_collab"
cat_norm: False
cat_softmax: False

# options = "pre-trans", "post-trans", "pre_contrast"
architecture: "post-trans"

# Self supervised options
device: 3
# Method for pooling img, depth, and location embeddings.1
# avg, max, random (select a random frame each time)
aggregation: "none"

save_path: "/trained_models/mmx/transformer/"